import { loadEnv } from './load-env';
loadEnv();

import fs from 'node:fs';
import path from 'node:path';

/**
 * Writes docs/salesforce-schema.md from the mapping table.
 *
 * Generated rather than hand-written so the document cannot drift from what the
 * adapter actually sends — a schema doc that disagrees with the code is worse
 * than none, because someone will build an org from it.
 *
 *   npm run generate-sf-docs
 */
async function main() {
  const { FIELD_MAPPINGS, UNWRITTEN_FIELDS, SOBJECT_ORDER, SOBJECT_LABELS } = await import('@/lib/salesforce/mapping');
  const { FIELD_SPECS_BY_PATH } = await import('@/shared/schema');

  const lines: string[] = [];
  const w = (line = '') => lines.push(line);

  w('# Salesforce schema');
  w();
  w('<!-- Generated by `npm run generate-sf-docs`. Edit lib/salesforce/mapping.ts instead. -->');
  w();
  w('Artificer writes two related records on approval: a `Property__c` and an');
  w('`Opportunity` that looks up to it.');
  w();
  w('## Where these names come from');
  w();
  w('They were derived from the public API behind nnnpro.com');
  w('(`api.surmount.com/sf-opportunities`), which serves a Salesforce replica —');
  w('every record carries a `salesforce_id`, and the replica nests an `sf_property`');
  w('inside each opportunity. The replica\'s snake_case columns map back to');
  w('Salesforce API names by the usual convention.');
  w();
  w('The strongest evidence is `x1031_exchange`: Salesforce prefixes an `X` to any');
  w('API name that would otherwise start with a digit, so that column can only have');
  w('come from `X1031_Exchange__c`. Standard Opportunity fields corroborate it —');
  w('`stage_name` ← `StageName`, `close_date` ← `CloseDate`.');
  w();
  w('Each field below records its origin:');
  w();
  w('| Origin | Meaning |');
  w('| --- | --- |');
  w('| **observed** | The replica column was seen on the live API; the API name follows from it. |');
  w('| **standard** | A standard Salesforce field, corroborated by the replica. |');
  w('| **proposed** | Artificer extracts this but no matching field was observed. Create it, or drop the mapping. |');
  w();
  w('> Casing caveat: snake_case is lossy, so `Building_Size_SF__c` could be');
  w('> `Building_Size_Sf__c` in the org. Salesforce resolves field names');
  w('> case-insensitively, so this is a cosmetic risk rather than a breaking one.');
  w();

  for (const object of SOBJECT_ORDER) {
    const forObject = FIELD_MAPPINGS.filter((m) => m.object === object);
    w(`## ${object} — ${SOBJECT_LABELS[object]}`);
    w();
    w('| Field | API name | Replica column | Origin | From |');
    w('| --- | --- | --- | --- | --- |');
    for (const m of forObject) {
      const from = m.path ? `\`${m.path}\`` : '_derived_';
      w(`| ${m.label} | \`${m.api}\` | ${m.replica ? `\`${m.replica}\`` : '—'} | ${m.origin} | ${from} |`);
    }
    w();
    const notes = forObject.filter((m) => m.note);
    if (notes.length) {
      for (const m of notes) w(`- **\`${m.api}\`** — ${m.note}`);
      w();
    }
  }

  w('## Relationship');
  w();
  w('```');
  w('Property__c  <──lookup──  Opportunity');
  w('```');
  w();
  w('`Property__c` is written first, because the Opportunity\'s lookup needs its id.');
  w();

  w('## Fields Artificer extracts but does not write');
  w();
  w('| Field | Why |');
  w('| --- | --- |');
  for (const item of UNWRITTEN_FIELDS) {
    const spec = FIELD_SPECS_BY_PATH[item.path];
    w(`| ${spec?.label ?? item.path} (\`${item.path}\`) | ${item.reason} |`);
  }
  w();
  w('These are still extracted, cited and reviewed — a reviewer should check a');
  w('stated cap rate against price and NOI, and a mismatch is worth catching. They');
  w('are simply not written, because the listing derives them.');
  w();

  const proposed = FIELD_MAPPINGS.filter((m) => m.origin === 'proposed');
  w('## Org changes required');
  w();
  w(`${proposed.length} field${proposed.length === 1 ? '' : 's'} below ${proposed.length === 1 ? 'was' : 'were'} not observed on the public model and must be created:`);
  w();
  w('| Object | API name | Type | Notes |');
  w('| --- | --- | --- | --- |');
  for (const m of proposed) {
    const spec = m.path ? FIELD_SPECS_BY_PATH[m.path] : undefined;
    const type = spec?.kind === 'number' ? 'Number' : spec?.kind === 'date' ? 'Date' : 'Text';
    w(`| \`${m.object}\` | \`${m.api}\` | ${type} | ${m.note ?? ''} |`);
  }
  w();
  w('`Deal_Hash__c` must be marked **External ID** and **Unique** — it is what makes');
  w('re-approval update the existing records instead of creating duplicates.');
  w();

  w('## Picklists');
  w();
  w('Two fields are picklist-backed on the public site, and their options are served');
  w('publicly:');
  w();
  w('```');
  w('GET /sf-opportunities/public/property-dropdown-options/concept');
  w('GET /sf-opportunities/public/visible-property-types');
  w('```');
  w();
  w('`Concept__c` matters most: it drives the Concept filter on the marketplace, so a');
  w('free-text value produces a listing that no filter can find. Artificer currently');
  w('extracts the tenant trade name as free text. Validating it against the live');
  w('picklist at extraction time is the single highest-value change to make next.');
  w();

  w('## Switching to a real org');
  w();
  w('```');
  w('SF_LOGIN_URL=https://login.salesforce.com   # or test.salesforce.com for a sandbox');
  w('SF_USERNAME=integration@example.com');
  w('SF_PASSWORD=<password><security token>      # concatenated, no separator');
  w('SF_INSTANCE_URL=https://your-domain.my.salesforce.com   # optional, enables link-out');
  w('```');
  w();
  w('All three of the first are required together; a partial configuration');
  w('deliberately falls back to mock rather than failing at the moment of approval.');
  w();
  w('Because the marketplace reads from a Salesforce replica, writing here *is*');
  w('publishing — an approved deal reaches nnnpro.com through the sync that already');
  w('exists. That is precisely why the approval gate sits where it does.');

  const target = path.join(process.cwd(), 'docs', 'salesforce-schema.md');
  fs.writeFileSync(target, lines.join('\n'));
  console.log(`Wrote ${path.relative(process.cwd(), target)} — ${FIELD_MAPPINGS.length} mappings, ${proposed.length} requiring org changes.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
